
BOUT_TOP = ../..

DIRS            = parderiv laplace
SOURCEC		= fft_fftw.cxx invert_laplace_gmres.cxx inverter.cxx lapack_routines.cxx
SOURCEH		= fft.hxx invert_laplace_gmres.hxx invert_parderiv.hxx inverter.hxx lapack_routines.hxx
TARGET		= lib

include $(BOUT_TOP)/make.config
