
BOUT_TOP = ../..

DIRS            = parderiv laplace laplacexy laplacexz laplacexy2
SOURCEC		= fft_fftw.cxx lapack_routines.cxx
SOURCEH		= fft.hxx invert_parderiv.hxx lapack_routines.hxx
TARGET		= lib

include $(BOUT_TOP)/make.config
