#!/bin/bash

# Run the laplace benchmark test on a range of core counts

EXE=laplace
FLAGS="-q -q -q -q"

make || exit

for NP in 1 2 4
do
    echo "Running laplace benchark on ${NP} cores"
    mpirun -np ${NP} ./${EXE} ${FLAGS}
done

