#!/bin/bash

# Run the laplace benchmark test on a range of core counts and grids

GRID_SIZES=(260) #16) # 32 64)
PROC_COUNTS=(1) # 4)
EXE=laplace
FLAGS="" #-q -q -q -q"

make || exit

for NX in ${GRID_SIZES[@]}
do
  for NP in ${PROC_COUNTS[@]}
  do
    echo "Running laplace benchark on ${NP} cores with nx ${NX}"
    mpirun --use-hwthread-cpus -np ${NP} ./${EXE} ${FLAGS} mesh:nx=${NX} NXPE=${NP} laplace:type=1dmg
  done
done

