#!/usr/bin/env python3

from boututils.run_wrapper import shell_safe, launch_safe, getmpirun

from sys import exit

nthreads = 1
nproc = 1
MPIRUN = getmpirun()

print("Making solver test")
shell_safe("make > make.log")

print("Running solver test")
s, out = launch_safe("./test_solver", runcmd=MPIRUN, nproc=nproc, mthread=nthreads, pipe=True)
with open("run.log", "w") as f:
    f.write(out)

exit(s)
