#!/usr/bin/env python

# 
# Run the test, check it completed successfully
#

from boututils import shell,launch,getmpirun
from boutdata import collect
from sys import stdout, exit

MPIRUN=getmpirun()

print "Making parallel inversion test"

shell("make > make.log")

flags = ["acoef=1 bcoef=0", "acoef=1 bcoef=-2", "acoef=1.5 'bcoef=2.*sin(2*y)'"]

code = 0 # Return code
for nproc in [1,2,4]:
    cmd = "./test_invpar"
    
    print "   %d processors...." % (nproc)
    r = 0
    for f in flags:
        stdout.write("\tflags '"+f+"' ... ")
        
        shell("rm data/BOUT.dmp.* 2> err.log")
        
        # Run the case
        s, out = launch(cmd+" "+f, runcmd=MPIRUN, nproc=nproc, pipe=True, verbose=True)
        f = open("run.log."+str(nproc)+"."+str(r), "w")
        f.write(out)
        f.close()
        r = r + 1
        
        # Find out if it worked
        allpassed = collect("allpassed", path="data", info=False)
        if allpassed:
            print "PASSED"
        else:
            print "FAILED"
            code = 1

if code == 0:
    print " => All inversion tests passed"
else:
    print " => Some failed tests"

exit(code)
