#pragma once

#ifndef BOUT_BUILD_CONFIG_HXX

#define BOUT_BUILD_CONFIG_HXX

 

#define BOUT_CHECK_LEVEL 2

//#define BOUT_FLAGS_STRING  -DBOUT_HAS_RAJA -DBOUT_HAS_UMPIRE -DBOUT_USE_CUDA -DBOUT_HAS_HYPRE -DCHECK=2      -Wall -Wextra -g

#define BOUT_OPENMP_SCHEDULE static

#define BOUT_HAS_ARKODE 1

#define BOUT_HAS_CVODE 1

#define BOUT_HAS_FFTW 1

#define BOUT_HAS_GETTEXT 1

#define BOUT_HAS_HDF5 0

#define BOUT_HAS_HYPRE 1

#define BOUT_HAS_IDA 1

#define BOUT_HAS_LAPACK 1

#define BOUT_HAS_NETCDF 1

#define BOUT_HAS_PETSC 1

#define BOUT_HAS_PRETTY_FUNCTION 1

#define BOUT_HAS_PVODE 1

#define BOUT_HAS_SCOREP 0

#define BOUT_HAS_SLEPC 0

#define BOUT_HAS_SUNDIALS 1

#define BOUT_USE_BACKTRACE 1

#define BOUT_USE_COLOR 1

#define BOUT_USE_OPENMP 0

#define BOUT_USE_OUTPUT_DEBUG 0

#define BOUT_USE_SIGFPE 0

#define BOUT_USE_SIGNAL 1

#define BOUT_USE_TRACK 1

#define BOUT_HAS_UMPIRE True   

#define BOUT_HAS_RAJA True 

#define BOUT_USE_CUDA True 

 

#endif // BOUT_BUILD_CONFIG_HXX
