/**************************************************************************
 * Reusable PETSc coloring-based Jacobian preconditioner support
 *
 * This class factors out the duplicated code in PETSc-based solvers for:
 * - building a Jacobian sparsity pattern (via stencil assumptions)
 * - creating a MatFDColoring context for efficient finite-difference Jacobians
 *
 **************************************************************************/

#ifndef BOUT_PETSC_PRECONDITIONER_H
#define BOUT_PETSC_PRECONDITIONER_H

#include "bout/bout_enum_class.hxx"
#include "bout/build_defines.hxx"

BOUT_ENUM_CLASS(PetscMatrixExportFormat, binary, ascii);

#if BOUT_HAS_PETSC

#include "bout/petsc_interface.hxx"
#include "bout/petsclib.hxx"

#include <mpi.h>

#include <petscmat.h>
#include <petscvec.h>

#include <string>

class Options;
class Field3D;

class PetscPreconditioner {
public:
  PetscPreconditioner() = default;
  ~PetscPreconditioner() { reset(); }

  PetscPreconditioner(const PetscPreconditioner&) = delete;
  PetscPreconditioner& operator=(const PetscPreconditioner&) = delete;
  PetscPreconditioner(PetscPreconditioner&&) = delete;
  PetscPreconditioner& operator=(PetscPreconditioner&&) = delete;

  /// Create and assemble a finite-difference Jacobian matrix `Jfd` with a sparsity
  /// pattern derived from the solver's variable layout and a user-specified stencil.
  ///
  /// `index` should be generated by the calling solver (e.g. `Solver::globalIndex(0)`).
  /// Safe to call multiple times; any existing PETSc objects are destroyed first.
  PetscErrorCode createJacobianPattern(Field3D& index, Options& options, PetscInt nlocal,
                                       int n2d, int n3d, MPI_Comm comm);

  /// Recalculate the PETSc coloring and finite-difference coloring context
  /// for the currently stored `Jfd` matrix.
  template <class ColoringFunction>
  PetscErrorCode updateColoring(ColoringFunction function, void* ctx) {
    // Re-calculate the coloring
    MatColoring coloring{nullptr};
    PetscCall(MatColoringCreate(Jfd, &coloring));
    PetscCall(MatColoringSetType(coloring, MATCOLORINGGREEDY));
    PetscCall(MatColoringSetFromOptions(coloring));

    // Calculate new index sets
    ISColoring iscoloring{nullptr};
    PetscCall(MatColoringApply(coloring, &iscoloring));
    PetscCall(MatColoringDestroy(&coloring));

    // Replace the old coloring with the new one
    PetscCall(MatFDColoringDestroy(&fdcoloring));
    PetscCall(MatFDColoringCreate(Jfd, iscoloring, &fdcoloring));
    PetscCall(
        MatFDColoringSetFunction(fdcoloring, bout::cast_MatFDColoringFn(function), ctx));
    PetscCall(MatFDColoringSetFromOptions(fdcoloring));
    PetscCall(MatFDColoringSetUp(Jfd, iscoloring, fdcoloring));
    PetscCall(ISColoringDestroy(&iscoloring));

    PetscFunctionReturn(PETSC_SUCCESS);
  }

  Mat jacobian() const { return Jfd; }
  MatFDColoring coloring() const { return fdcoloring; }

  static PetscErrorCode
  saveMatrix(Mat matrix, const std::string& filename,
             PetscMatrixExportFormat format = PetscMatrixExportFormat::binary);
  PetscErrorCode
  saveMatrix(const std::string& filename,
             PetscMatrixExportFormat format = PetscMatrixExportFormat::binary) const;

  void reset();

private:
  Mat Jfd{nullptr};
  MatFDColoring fdcoloring{nullptr};
};

#else

// PETSc is not available, but keep the type defined so headers can be included
// unconditionally in PETSc-enabled compilation units.
class PetscPreconditioner {
public:
  void saveMatrix(
      const std::string& UNUSED(filename),
      PetscMatrixExportFormat UNUSED(format) = PetscMatrixExportFormat::binary) const {}
  void reset() {}
};

#endif // BOUT_HAS_PETSC

#endif // BOUT_PETSC_PRECONDITIONER_H
