version: 2

updates:
  - package-ecosystem: "gitsubmodule"
    schedule:
        interval: "weekly"
    directory: "/"

  - package-ecosystem: "pip"
    schedule:
        interval: "daily"
    directory: "/"
  
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    directory: "/"
