[build-system]
# Defined by PEP 518:
requires = []
# Defined by PEP 517:
build-backend = "backend"
backend-path = ["tools/pylib/_boutpp_build/"]

[tool.pytest.ini_options]
console_output_style = "plain"

[dependency-groups]
dev = [
     "cmake~=4.4",
     "clang-format~=22.1",
     "clang-tidy~=22.1",
     "clangd~=22.1",
     "clangd-tidy~=1.1",
     "cmakelang~=0.6",
     "prek>=0.3.10",
     "pyyaml~=6.0",
     "ruff~=0.16",
     "sphinx-lint~=1.0",
     "sync-with-uv~=0.6.0",
]
pytest = [
     "pytest~=9.1",
     "pytest-xdist~=3.8",
]
maint = [
      "pygithub~=2.10",
      "ruamel-yaml~=0.19",
      "Unidecode~=1.4",
]

[tool.uv.workspace]
