#!/bin/bash

#requires: all_tests
#Requires: not make

BOUT_TOP=../../..
export PATH=$BOUT_TOP/bin:$PATH

error=0

failed=
for header in $(cd $BOUT_TOP/include ; find |grep hxx\$)
do
    echo "#include <$header>" > test.cxx

    $(bout-config --cxx) $(bout-config --cflags) test.cxx -c

    ex=$?
    
    if test $ex -gt 0
    then
        echo $header failed
        error=1
	failed="$failed
$header failed"
    fi

done

echo $failed

exit $error
