#!/usr/bin/env python3

# Python script to run and analyse MMS test

import sys

from boutdata.collect import collect
from boututils.run_wrapper import build_and_log, launch_safe, shell
from numpy import abs, array, log, max, mean, sqrt

build_and_log("MMS diffusion test")

# List of NX values to use
nxlist = [4, 8, 16, 32, 64, 128]

nout = 1
timestep = 0.1

nproc = 1

error_2 = []  # The L2 error (RMS)
error_inf = []  # The maximum error

for nx in nxlist:
    # Set the mesh size, ouput steps and timestep. Replace previous outputs if present.
    args = (
        "mesh:nx="
        + str(nx)
        + " nout="
        + str(nout)
        + " timestep="
        + str(timestep)
        + " replace"
    )

    print("Running with " + args)

    # Delete old data
    shell("rm data/BOUT.dmp.*.nc")

    # Command to run
    cmd = "./cyto " + args
    # Launch using MPI
    s, out = launch_safe(cmd, nproc=nproc, pipe=True)

    # Save output to log file
    with open("run.log." + str(nx), "w") as f:
        f.write(out)

    # Collect data
    E_N = collect("E_N", tind=[nout, nout], path="data", info=False)

    E_N = E_N[0, :, 0, 0]

    # Average error over domain, not including guard cells
    l2 = sqrt(mean(E_N[1:-1] ** 2))
    linf = max(abs(E_N[1:-1]))

    error_2.append(l2)
    error_inf.append(linf)

    print(f"Error norm: l-2 {l2} l-inf {linf}")

# Calculate grid spacing
dx = 1.0 / (array(nxlist) - 2.0)

order = log(error_2[-1] / error_2[-2]) / log(dx[-1] / dx[-2])
print(f"Convergence order = {order}")

# Attempt to plot errors
try:
    import matplotlib.pyplot as plt

    plt.plot(dx, error_2, "-o", label=r"$l^2$")
    plt.plot(dx, error_inf, "-x", label=r"$l^\infty$")
    plt.plot(dx, error_2[-1] * (dx / dx[-1]) ** order, "--", label=f"Order {order}")

    plt.legend(loc="upper left")
    plt.grid()

    plt.yscale("log")
    plt.xscale("log")

    plt.xlabel(r"Mesh spacing $\delta x$")
    plt.ylabel("Error norm")

    plt.savefig("norm.pdf")

    # plt.show()
    plt.close()
except Exception as e:  # noqa: BLE001
    # Plotting could fail for any number of reasons, and the actual
    # error raised may depend on, among other things, the current
    # matplotlib backend, so catch everything
    print(f"Plotting: Caught exception {e}")

if order > 1.8 and order < 2.2:
    # test for success
    print(" => Test passed")
    sys.exit(0)
else:
    print(" => Test failed")
    sys.exit(1)
