
BOUT_TOP = ../..

SOURCEC		= difops.cpp grid.cpp interpolation.cpp mesh.cpp boutmesh.cpp boundary_standard.cpp boundary_factory.cpp boundary_region.cpp
SOURCEH		= $(SOURCEC:%.cpp=%.h)
TARGET		= lib

include $(BOUT_TOP)/make.config
