
BOUT_TOP = ../..

SOURCEC		= communicator.cpp difops.cpp grid.cpp interpolation.cpp mesh_topology.cpp mesh.cpp boutmesh.cpp
SOURCEH		= $(SOURCEC:%.cpp=%.h)
INCLUDE		= -I../sys -I../field -I../fileio -I../invert
TARGET		= lib

include $(BOUT_TOP)/make.config
