
BOUT_TOP = ../..

SOURCEC		= communicator.cpp difops.cpp geometry.cpp grid.cpp	interpolation.cpp mesh_topology.cpp
SOURCEH		= $(SOURCEC:%.cpp=%.h)
INCLUDE		= -I../sys -I../field -I../fileio -I../invert
TARGET		= lib

include $(BOUT_TOP)/make.config
