
BOUT_TOP = ../../..

DIRS		= arkode \
	pvode cvode ida \
	petsc-3.1 petsc-3.2 petsc-3.3 petsc-3.4 petsc-3.5 petsc \
	snes imex-bdf2 \
	power slepc-3.4 \
	karniadakis rk4 euler rk3-ssp rkgeneric
TARGET		= lib

include $(BOUT_TOP)/make.config
