
BOUT_TOP = ../../..

DIRS		= arkode \
	pvode cvode ida \
	petsc \
	snes imex-bdf2 \
	power slepc adams_bashforth \
	rk4 euler rk3-ssp rkgeneric split-rk

TARGET		= lib

include $(BOUT_TOP)/make.config
