
set(tpl_prefix "/usr/WS2/BOUT-GPU/lassen/env/tpl" CACHE STRING "")
set(tpl_install_prefix "/${tpl_prefix}/install/ppc64le-gcc" CACHE STRING "")
set(module_prefix "/usr/WS2/BOUT-GPU/lassen/env/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.1" CACHE STRING "")

set(CMAKE_CXX_COMPILER "mpiCC" CACHE STRING "")
set(CMAKE_CXX_STANDARD "14" CACHE STRING "")
set(CMAKE_C_COMPILER "mpicc" CACHE STRING "")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")

set(CMAKE_PREFIX_PATH "${tpl_install_prefix}/raja/share/raja/cmake;${tpl_install_prefix}/umpire/share/umpire/cmake" CACHE BOOL "")
set(NCXX4_CONFIG "${module_prefix}/netcdf-cxx4-4.3.1-sj65c6a4kyaaw3d6dopj6txamfkli3dc/bin/ncxx4-config" CACHE FILEPATH "")
set(NC_CONFIG "${module_prefix}/netcdf-c-4.7.4-7x3quj36clrfnejvxqyb5ky6gbco73zr/bin/nc-config" CACHE FILEPATH "")

set(USE_NETCDF ON CACHE BOOL "")
set(USE_FFTW ON CACHE BOOL "")
set(USE_LAPACK ON CACHE BOOL "")
set(USE_NLS ON CACHE BOOL "")
set(ENABLE_PETSC ON CACHE BOOL "")
set(PETSC_DIR "${module_prefix}/petsc-3.13.0-7b3be6747en6tm2v4ifa4zri556pdcxl" CACHE PATH "")
set(ENABLE_HYPRE ON CACHE BOOL "")
set(HYPRE_DIR "${tpl_prefix}/hypre_automake/install" CACHE PATH "")
set(HYPRE_CUDA ON CACHE BOOL "")
set(USE_PVODE ON CACHE BOOL "")
set(USE_SUNDIALS ON CACHE BOOL "")
set(ENABLE_RAJA ON CACHE BOOL "")
set(ENABLE_UMPIRE OFF CACHE BOOL "")
set(ENABLE_MPI ON CACHE BOOL "")
set(ENABLE_OPENMP OFF CACHE BOOL "")
set(ENABLE_CUDA ON CACHE BOOL "")
set(CUDA_ARCH sm_70 CACHE BOOL "")
set(CMAKE_CUDA_STANDARD 14 CACHE BOOL "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "")
set(ENABLE_GTEST ON CACHE BOOL "")
set(ENABLE_GMOCK ON CACHE BOOL "")
set(BUILD_GTEST OFF CACHE BOOL "")
set(BUILD_TESTING ON CACHE BOOL "")
set(ENABLE_TESTS ON CACHE BOOL "")
set(PACKAGE_TESTS ON CACHE BOOL "")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "")
set(CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "")
set(gtest_disable_pthreads ON CACHE BOOL "")

set(CMAKE_INSTALL_RPATH "${module_prefix}/petsc-3.13.0-7b3be6747en6tm2v4ifa4zri556pdcxl/lib;${module_prefix}/hdf5-1.10.6-zkwocrtngfhf5nw6xk5c4cbekrdycznu/lib" CACHE PATH "")
set(CMAKE_BUILD_RPATH "${module_prefix}/petsc-3.13.0-7b3be6747en6tm2v4ifa4zri556pdcxl/lib;${module_prefix}/hdf5-1.10.6-zkwocrtngfhf5nw6xk5c4cbekrdycznu/lib" CACHE PATH "")
