#!/usr/bin/env python

#
# Runs the conduction example, produces some output
# 

nproc = 2  # Number of processors to use

from boututils import shell, launch, plotdata
from boutdata import collect
import numpy as np

print "Making conduction example"
shell("make > make.log")

s, out = launch("./conduction ", nproc=nproc, pipe=True)
f = open("run.log", "w") # Save the output in a log file
f.write(out)
f.close()

# Collect the data
T = collect("T", path="data", xind=2, info=True, yguards=True)

# T has dimensions [Time, X, Y, Z]
# Make contour plot
plotdata.plotdata(T[:,0,:,0])
