
BOUT_TOP = ../../../..

DIRS            = serial_tri serial_band pdd spt petsc mumps cyclic shoot multigrid naulin parallel_tri parallel_tri_multigrid parallel_tri_multigrid_new

include $(BOUT_TOP)/make.config
