
BOUT_TOP = ../..

SOURCEC		= fft_fftw.cpp invert_laplace.cpp invert_laplace_gmres.cpp invert_parderiv.cpp inverter.cpp lapack_routines.cpp
SOURCEH		= fft.h invert_laplace.h invert_laplace_gmres.h invert_parderiv.h inverter.h lapack_routines.h
TARGET		= lib

include $(BOUT_TOP)/make.config