#!/usr/bin/env python3

#
# Run the test, check it completed successfully
#

#requires: all_tests

from __future__ import print_function
try:
    from builtins import str
except:
    pass
from boututils.run_wrapper import shell, shell_safe, launch, getmpirun
from boutdata.collect import collect
from sys import stdout, exit

MPIRUN=getmpirun()

print("Making DataIterator test")
shell_safe("make > make.log",pipe=True)
errors=[]

for nproc in [1,2,4]:
    for mproc in [1,2,3,4]:
        cmd = "./test_dataiterator"

        print("   %d x %d threads...." % (nproc,mproc))

        shell("rm data/BOUT.dmp.* 2> err.log")

        # Run the case
        s, out = launch(cmd, runcmd=MPIRUN, nproc=nproc, mthread=mproc, pipe=True)
        with open("run.log."+str(nproc)+"."+str(mproc), "w") as f:
            f.write(out)
        if s:
            errors.append([n,m,s,out])

if errors:
    print(" => Some data iteration tests failed")
    for n,m,s,out in errors:
        print("Run with n=%d mpi threads and m=%d openmp threads failed.",n,m)
    print()
    for n,m,s,out in errors:
        print(" * Run n=%d m=%d - exit %d\nError was:\n\n%s\n\n",n,m,s,out)
    print()
    exit(1)
else:
    print(" => All data iteration tests passed")
