#!/usr/bin/env python3

#
# Run the test, check it completed successfully
#

from __future__ import print_function
try:
    from builtins import str
except:
    pass
from boututils.run_wrapper import shell, shell_safe, launch_safe, getmpirun
from boutdata.collect import collect
from sys import stdout, exit

MPIRUN=getmpirun()

print("Making DataIterator test")
s, out = shell_safe("make > make.log",pipe=True)

flags = [""]

for nproc in [1,2,4]:
    for mproc in [1,2,4,8]:
        cmd = "./test_dataiterator"

        print("   %d processors...." % (nproc))

        for f in flags:
            stdout.write("\tflags '"+f+"' ... ")

            shell("rm data/BOUT.dmp.* 2> err.log")

            # Run the case
            _, out = launch_safe(cmd+" "+f, runcmd=MPIRUN, nproc=nproc, pipe=True)
            with open("run.log."+str(nproc)+"."+str(mproc), "w") as f:
                f.write(out)

print(" => All data iteration tests passed")
