#!/usr/bin/env python3

from boututils.run_wrapper import build_and_log, launch_safe

from sys import exit

build_and_log("Evolve scalar test")

print("Running evovle solver test")
status, out = launch_safe("./test_solve_scalar", nproc=1, mthread=1, pipe=True)
with open("run.log", "w") as f:
    f.write(out)

if status:
    print(out)

exit(status)
