#!/usr/bin/env python3

# 
# Run the test, compare results against the benchmark
#

from __future__ import print_function
try:
  from builtins import str
except:
  pass

# Variables to compare
vars =  ['flag0', 'flag3', 'flagis', 'flagos', # pass robust to omega under-relaxation
         'flag0a', 'flag3a', 'flagisa', 'flagosa',
         'flag0ac', 'flag3ac','flagisac', 'flagosac',
         'flag0ad', 'flag3ad', 'flagisad', 'flagosad']  
tol = 1e-6                  # Absolute tolerance

from boututils.run_wrapper import shell, shell_safe, launch_safe
from boutdata.collect import collect
import numpy as np
from sys import stdout, exit



print("Making Laplacian inversion test")
shell("rm test_laplace")
shell_safe("make > make.log")

# Read benchmark values
print("Reading benchmark data")
bmk = {}
for v in vars:
  bmk[v] = collect(v, path="data", prefix="benchmark", info=False)

print("Running Laplacian inversion test")
success = True

maxits=1000

for nproc in [2,4]:
  nxpe = 1
  if nproc > 1:
    #nxpe = 2
    nxpe = nproc
  
  cmd = "./test_laplace nxpe=" + str(nxpe) + " laplace:maxits=" + str(maxits)
  
  shell("rm data/BOUT.dmp.*.nc")

  print("   %d processors (nxpe = %d)...." % (nproc, nxpe))
  s, out = launch_safe(cmd, nproc=nproc, mthread=1, pipe=True)
  with open("run.log."+str(nproc), "w") as f:
    f.write(out)

   # Collect output data
  for v in vars:
    stdout.write("      Checking variable "+v+" ... ")
    result = collect(v, path="data", info=False)
    #np.savetxt("its_"+str(maxits)+".txt",result[:,2,0])
    #print(np.shape(result))
    #print(result[:,2,0])
    #print(bmk[v][:,2,0])
    #print(result[:,2,0]/bmk[v][:,2,0])
    #np.savetxt("bm.txt",bmk[v][:,2,0])
    skipped = collect(v+"_error", path="data", info=False)
    if skipped:
        for ix, _ in enumerate(result[:,0,0]):
            for iy, _ in enumerate(result[0,:,0]):
                for iz, _ in enumerate(result[0,0,:]):
                    #if iz==0:
                    #    continue
                    if abs(result[ix,iy,iz]-bmk[v][ix,iy,iz]) > 1.0e-6:
                        #print(ix,iy,iz,result[ix,iy,iz],bmk[v][ix,iy,iz])
                        pass
    # Compare benchmark and output
    if np.shape(bmk[v]) != np.shape(result):
      print("Fail, wrong shape")
      success = False
    diff = np.max(np.abs(bmk[v][:,:,:] - result[:,:,:]))
    if skipped:
      print("Expected failure")
    elif diff > tol:
      print("Fail, maximum difference = "+str(diff))
      success = False
    else:
      print("Pass")

if success:
  print(" => All Laplacian inversion tests passed")
  exit(0)
else:
  print(" => Some failed tests")
  exit(1)
