#!/bin/bash

BOUT_TOP=../../..
error=

for i in BoutReal # double float int char size_t
do
    grep -E "\([^\)]*const[^\(,:<]*$i[^,\):\*>]*\&"  -r --include=*xx $BOUT_TOP &&
        error=yes &&
        echo "const $i should be passed by value"
done
#for emacs regexp: \([,\(]\)[[:space:]]*const[[:space:]]+\([A-Za-z]+\)[[:space:]]+\([A-Za-z0-9]+\)[[:space:]]*\([,\)]\) → \1\2 \3\4)
grep [\(,][[:space:]]*const[[:space:]][[:alnum:]]*[[:space:]][[:alnum:]]*[[:space:]]*[,\)] -r --include=*hxx $BOUT_TOP -n &&
    error=yes &&
    echo "Declaration of functions shouldn't declare pass-by-value as const"

if test $error
then
    echo "-> Errors listed above"
    exit 1
else
    echo "No Errors detected"
    exit 0
fi
