
BOUT_TOP = ../..

DIRS			= impls
SOURCEC		= solver.cpp
SOURCEH		= $(SOURCEC:%.cpp=%.h)
INCLUDE		= -I../sys -I../field -I../physics -I../mesh -I../fileio
TARGET		= lib

include $(BOUT_TOP)/make.config
