
BOUT_TOP = ../..

SOURCEC		= generic_solver.cpp  $(SOLVER_SOURCE)
SOURCEH		= $(SOURCEC:%.cpp=%.h) solver.h
INCLUDE		= -I../sys -I../field -I../physics -I../mesh -I../fileio
TARGET		= lib

include $(BOUT_TOP)/make.config
