
BOUT_TOP = ../..
DIRS		= options
SOURCEC		= boutexception.cpp comm_group.cpp dcomplex.cpp derivs.cpp \
		  diagnos.cpp msg_stack.cpp options.cpp output.cpp \
		  stencils.cpp utils.cpp optionsreader.cpp boutcomm.cpp

SOURCEH		= $(SOURCEC:%.cpp=%.h) globals.h bout_types.h multiostream.h
TARGET		= lib

include $(BOUT_TOP)/make.config
