
BOUT_TOP = ../..
DIRS		= options
SOURCEC		= boutexception.cxx comm_group.cxx derivs.cxx \
		  msg_stack.cxx options.cxx output.cxx \
		  stencils.cxx utils.cxx optionsreader.cxx boutcomm.cxx \
		  timer.cxx range.cxx petsclib.cxx expressionparser.cxx \
	          slepclib.cxx

SOURCEH		= $(SOURCEC:%.cxx=%.hxx) globals.hxx bout_types.hxx multiostream.hxx
TARGET		= lib

include $(BOUT_TOP)/make.config
