#!/usr/bin/env python

# 
# Run the test, compare results against the benchmark
#

# Variables to compare
vars = ['pade1', 'pade2']
  
tol = 1e-5                  # Absolute tolerance

from boututils import shell,launch,getmpirun
from boutdata import collect
import numpy as np
from sys import stdout, exit

MPIRUN=getmpirun()

print "Making Gyro-average inversion test"
shell("make > make.log")

# Read benchmark values
print "Reading benchmark data"
bmk = {}
for v in vars:
  bmk[v] = collect(v, path="data", prefix="benchmark", info=False)

print "Running Gyro-average inversion test"
success = True

for nproc in [1,2,4]:
  nxpe = 1
  if nproc > 2:
    nxpe = 2
  
  cmd = "./test_gyro nxpe=" + str(nxpe)
  
  shell("rm data/BOUT.dmp.*.nc")

  print "   %d processors (nxpe = %d)...." % (nproc, nxpe)
  s, out = launch(cmd, runcmd=MPIRUN, nproc=nproc, pipe=True)
  f = open("run.log."+str(nproc), "w")
  f.write(out)
  f.close()
  
   # Collect output data
  for v in vars:
    stdout.write("      Checking variable "+v+" ... ")
    result = collect(v, path="data", info=False)
    # Compare benchmark and output
    if np.shape(bmk[v]) != np.shape(result):
      print "Fail, wrong shape"
      success = False
    diff =  np.max(np.abs(bmk[v] - result))
    if diff > tol:
      print "Fail, maximum difference = "+str(diff)
      success = False
    else:
      print "Pass"

if success:
  print " => All Gyro-average tests passed"
  exit(0)
else:
  print " => Some failed tests"
  exit(1)

