BOUT_TOP = ../../..

#DIRS            = impls data
SOURCEC		= fuu.cxx
#difops.cxx interpolation.cxx mesh.cxx boundary_standard.cxx boundary_factory.cxx boundary_region.cxx meshfactory.cxx surfaceiter.cxx fv_ops.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.hxx)
MODULE_DIR	= ..
SUB_NAME	= fuu
TARGET		= sub

include $(BOUT_TOP)/make.config
