
BOUT_TOP = ../../../../..

SOURCEC         = mumps_laplace.cxx
SOURCEH         = mumps_laplace.hxx
TARGET          = lib

#EXTRA_INCS += -I/home/jto500/src/MUMPS_4.10.0/include
#EXTRA_LIBS += -L/home/jto500/src/MUMPS_4.10.0/lib

# NB highly machine specific, need to include MUMPS in the global configure script instead of here
#CXXFLAGS +=-g -I/home/jto500/src/MUMPS_4.10.0/include -L/home/jto500/src/MUMPS_4.10.0/lib

include $(BOUT_TOP)/make.config
