#!/usr/bin/env python

# 
# Run the test, compare results against the benchmark
#

# Variables to compare
from __future__ import print_function
try:
  from builtins import str
except:
  pass

from boututils.run_wrapper import shell, launch, getmpirun
from boutdata.collect import collect
import numpy as np
from sys import stdout, exit

nproc = 1

MPIRUN=getmpirun()

print("Making stopCheck test")
shell("make > make.log")

checkVal=[True,False]
nstepExpect=[2,11]

vars=["t_array"]

print("Running stopCheck test")
success = True

for i, check in enumerate(checkVal):
    cmd = "./test_stopCheck"

    s, out = launch(cmd+" stopCheck="+str(check).lower(), runcmd=MPIRUN, nproc=nproc, pipe=True)
    f = open("run.log."+str(check).lower(), "w")
    f.write(out)
    f.close()
    
    # Collect output data
    for v in vars:
      result = collect(v, path="data", info=False)

      # Compare benchmark and output
      if result.shape[0] != nstepExpect[i]:
        print("Fail, wrong shape")
        print("Option is "+str(check))
        print("shape is "+str(result.shape[0]))
        print("expecting "+str(nstepExpect[i]))
        success = False
        continue

if success:
  print(" => All checkStop tests passed")
  exit(0)
else:
  print(" => Some failed tests")
  exit(1)
