#!/usr/bin/env python3

# requires: fftw
# cores: 4

from boututils.run_wrapper import build_and_log, shell, launch_safe
from boutdata.collect import collect
import numpy as np
from sys import stdout, exit

tol = 1e-10  # Absolute tolerance


# The command to run
exefile = "python3 test_delp2.py"


success = True

n0s = None
for nproc in [1, 2, 4]:
    shell("rm -f run?.dmp.*.nc")

    launch_safe(exefile, nproc=nproc, pipe=True)

    ns = [collect("n", path=".", info=False, prefix=f"run{i}.dmp") for i in range(2)]

    if n0s is None:
        n0s = ns
    else:
        for n0, n in zip(n0s, ns):

            if not n.shape == n0.shape:
                print("Fail, wrong shape")
                success = False
            diff = np.max(np.abs(n - n0))
            if diff > tol:
                print("Fail, maximum difference = " + str(diff))
                success = False
            else:
                print("Pass")

if success:
    print(" => All Delp2 tests passed")
    exit(0)
else:
    print(" => Some failed tests")
    exit(1)
