
BOUT_TOP = ../../..

DIRS            = 
SOURCEC		= bilinear.cxx hermite_spline.cxx monotonic_hermite_spline.cxx hermite_spline_only_z.cxx lagrange_4pt.cxx
TARGET		= lib

include $(BOUT_TOP)/make.config
