
BOUT_TOP = ../../..

DIRS            = 
SOURCEC         = bilinear_xz.cxx hermite_spline_xz.cxx \
                  monotonic_hermite_spline_xz.cxx lagrange_4pt_xz.cxx \
                  hermite_spline_only_z.cxx
TARGET          = lib

include $(BOUT_TOP)/make.config
