#!/usr/bin/env python

#
# Runs the conduction example, produces some output
#

from __future__ import print_function
from __future__ import division
from builtins import str
from builtins import range
from past.utils import old_div
nproc = 1  # Number of processors to use

from boututils.run_wrapper import shell, launch
from boutdata.plotdata import plotdata
from boutdata.collect import collect
import numpy as np
from sys import argv

slice_index = int(argv[1])
try:
  data_path = str(argv[2])
except:
  data_path = "data"

# Collect the data
q = collect("heat_flux", path=data_path, xind=2, info=True, yguards=True)

# q has dimensions [Time, X, Y, Z]
length=len(q[0,0,:,0])
for index, item in enumerate(q[slice_index,0,:,0]):
	print(index, item)

print("minimum_q =", min(q[slice_index,0,3:length-3,0]), " maximum_q =", max(q[slice_index,0,3:length-3,0]))
print(" ")
print("data_path is",data_path)

localminq=0
for i in range(old_div(length,2)-1,0,-1):
	test=q[slice_index,0,i,0]
	if test>localminq:
		break
	localminq=test

localmaxq=0
for i in range(old_div(length,2)+1,length):
	test=q[slice_index,0,i,0]
	if test<localmaxq:
		break
	localmaxq=test

print("localminq =", localminq, " localmaxq =", localmaxq)

# Make contour plot
plotdata(q[slice_index,0,:,0],title="Electron Heat Flux Profile at t="+str(argv[1]))
