#!/usr/bin/env python

#
# Runs the conduction example, produces some output
#

from __future__ import print_function
from builtins import str
nproc = 1  # Number of processors to use

from boututils.run_wrapper import shell, launch
from boutdata.plotdata import plotdata
from boutdata.collect import collect
import numpy as np
from sys import argv

slice_index = int(argv[1])
try:
  data_path = str(argv[2])
except:
  data_path = "data"

# Collect the data
R = collect("friction", path=data_path, xind=2, info=True, yguards=True)

# R has dimensions [Time, X, Y, Z]
length=len(R[0,0,:,0])
for index, item in enumerate(R[slice_index,0,:,0]):
	print(index, item)

# Make plot
plotdata(R[slice_index,0,:,0],title="Electron Friction Profile at t="+str(argv[1]))
