#!/usr/bin/env python

#
# Runs the conduction example, produces some output
# 

nproc = 1  # Number of processors to use

from boututils import shell, launch, plotdata
from boutdata import collect
import numpy as np
from sys import argv

slice_index = int(argv[1])
try:
  data_path = str(argv[2])
except:
  data_path = "data"

# Collect the data
T = collect("local_non-local_ratio", path=data_path, xind=2, info=True, yguards=True)

# T has dimensions [Time, X, Y, Z]
for index, item in enumerate(T[slice_index,0,:,0]):
	print index, item
# Make contour plot
plotdata.plotdata(T[slice_index,0,2:-2,0],title="Braginskii Heat Flux Over Non-Local Heat Flux")
