#!/usr/bin/env python

#
# Runs the conduction example, produces some output
#

from __future__ import print_function
from builtins import str
nproc = 1  # Number of processors to use

from boututils.run_wrapper import shell, launch
from boutdata.plotdata import plotdata
from boutdata.collect import collect
import numpy as np
from sys import argv

slice_index = int(argv[1])
try:
  data_path = str(argv[2])
except:
  data_path = "data"

# Collect the data
pi = collect("viscosity", path=data_path, xind=2, info=True, yguards=True)

# pi has dimensions [Time, X, Y, Z]
length=len(pi[0,0,:,0])
for index, item in enumerate(pi[slice_index,0,:,0]):
	print(index, item)

print("data_path is",data_path)

# Make plot
plotdata(pi[slice_index,0,:,0],title="Electron Viscosity Profile at t="+str(argv[1]))
