#!/usr/bin/env python

from __future__ import print_function
from builtins import str
from boututils.run_wrapper import shell, launch
from boutdata.plotdata import plotdata
from boutdata.collect import collect
import numpy as np
from sys import argv

if len(argv)==1:
  end_index = -1
  data_path = "data"
elif len(argv)==2:
  try:
    end_index = int(argv[1])
    data_path = "data"
  except ValueError:
    end_index = -1
    data_path = str(argv[1])
elif len(argv)==3:
  end_index = int(argv[1])
  data_path = str(argv[2])
else:
  print("Arguments: [end_index][data_path] or [data_path]")
  Exit(1)

# Collect the data
n = collect("n_ion", path=data_path, xind=2, info=True, yguards=True)

if end_index<0:
  end_index = len(n[:,0,0,0])

# n has dimensions [Time, X, Y, Z]
# Make contour plot
if len(argv)>1:
  plotdata(n[:end_index,0,:,0],title="n")
else:
  plotdata(n[:,0,:,0],title="n")

#print(n[204,:,:,:])
