#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
from builtins import str
from boututils import shell, launch, plotdata
from boutdata import collect
import numpy as np
from sys import argv

slice_index = int(argv[1])
try:
  data_path = str(argv[2])
except:
  data_path = "data"

# Collect the data
j = collect("j_parallel", path=data_path, xind=2, info=True, yguards=True)

# j has dimensions [Time, X, Y, Z]
for index, item in enumerate(j[slice_index,0,:,0]):
	print(index, item)
# Make contour plot
plotdata.plotdata(j[slice_index,0,:,0],title="Parallel Current Profile at t="+str(argv[1]),ytitle="j/Am^-2")
