#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Runs the conduction example, produces some output
#

from __future__ import print_function
from builtins import str
nproc = 1  # Number of processors to use

from boututils.run_wrapper import shell, launch
from boutdata.plotdata import plotdata
from boutdata.collect import collect
import numpy as np
from sys import argv

slice_index = int(argv[1])
try:
  data_path = str(argv[2])
except:
  data_path = "data"

# Collect the data
T = collect("T_electron", path=data_path, xind=2, info=True, yguards=True)

# T has dimensions [Time, X, Y, Z]
for index, item in enumerate(T[slice_index,0,:,0]):
	print(index, item)
# Make contour plot
plotdata(T[slice_index,0,:,0],title="Electron Temperature Profile at t="+str(argv[1]),ytitle="T/eV")
