#!/usr/bin/env python

#
# Runs the conduction example, produces some output
# 

from __future__ import print_function
from builtins import str
nproc = 1  # Number of processors to use

from boututils import shell, launch, plotdata
from boutdata import collect
import numpy as np
from sys import argv

slice_index = int(argv[1])
try:
  data_path = str(argv[2])
except:
  data_path = "data"

# Collect the data
T = collect("n_ion", path=data_path, xind=2, info=True, yguards=True)

# T has dimensions [Time, X, Y, Z]
print(T[slice_index,0,:,0])
# Make contour plot
#plotdata.plotdata(T[:,0,:,0])
plotdata.plotdata(T[slice_index,0,:,0])
