#!/usr/bin/env python

#
# Runs the conduction example, produces some output
#

from __future__ import print_function
from builtins import str
nproc = 1  # Number of processors to use

from boututils.run_wrapper import shell, launch
from boutdata.plotdata import plotdata
from boutdata.collect import collect
import numpy as np
from sys import argv

slice_index = int(argv[1])
try:
  data_path = str(argv[2])
except:
  data_path = "data"

# Collect the data
T = collect("T_ion", path=data_path, xind=2, info=True, yguards=True)
#chi = collect("chi", path="data", xind=2, info=True, yguards=True)
#integral = collect("integral", path="data", xind=2, info=True, yguards=True)
#q = collect("heat_flux", path="data", xind=2, info=True, yguards=True)

# T has dimensions [Time, X, Y, Z]
print(T[slice_index,0,:,0])
# Make contour plot
plotdata(T[slice_index,0,2:-3,0],title="Ion Temperature Profile at t="+str(argv[1]),ytitle="T/eV")
