
BOUT_TOP	= ../..

SOURCEC		= cubic_spline_local.cxx non-local_parallel.cxx non-local_parallel_integration.cxx non-local_1d.cxx
SOURCEH		= cubic_spline_local.hxx non-local_parallel.hxx non-local_parallel_integration.hxx
TARGET		= non-local_1d

CXXFLAGS += -g

include $(BOUT_TOP)/make.config
