
BOUT_TOP = ../..

DIRS			= impls
SOURCEC		= solver.cpp solverfactory.cpp
SOURCEH		= $(SOURCEC:%.cpp=%.h)
INCLUDE		= -Iimpls/cvode -Iimpls/ida -Iimpls/petsc -Iimpls/pvode
TARGET		= lib

include $(BOUT_TOP)/make.config
