
BOUT_TOP = ../..

DIRS			= impls
SOURCEC		= solver.cxx solverfactory.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.h)
INCLUDE		= -Iimpls/cvode -Iimpls/ida -Iimpls/petsc -Iimpls/pvode
TARGET		= lib

include $(BOUT_TOP)/make.config
