package:
  name: bunch
  version: !!str 1.0.1

source:
  fn: bunch-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/b/bunch/bunch-1.0.1.tar.gz
  md5: 0a829d64e95ed96defbcae2bf9061bb0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bunch = bunch:main
    #
    # Would create an entry point called bunch that calls bunch.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - bunch

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/dsc/bunch
  license:  MIT License
  summary: 'A dot-accessible dictionary (a la JavaScript objects)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
