#!/usr/bin/env python3

#
# Run the test, compare results against the benchmark
#

from boututils.run_wrapper import shell, shell_safe,launch_safe,getmpirun
from boutdata import collect
from numpy import sqrt, max, abs, mean, array, log, pi, polyfit, meshgrid, exp, sin, cos
from sys import stdout, exit
import matplotlib.pyplot as plt
from scipy import interpolate
from scipy.interpolate import interp2d

# List of NX values to use
nxlist = [16, 32, 64, 128, 256, 512]

# Only testing 2D (x, z) slices, so only need one processor
nproc = 1

# Variables to compare
varlist = ['a', 'b', 'c']
markers = ['bo', 'r^', 'kx']
labels = [r'$'+var+r'$' for var in varlist]

MPIRUN=getmpirun()

print("Making Interpolation test")
shell_safe("make > make.log")

print("Running Interpolation test")
success = True

error_2 = {}
error_inf = {}
for var in varlist:
    error_2[var] = []             # L2 error (RMS)
    error_inf[var] = []           # Maximum error

for nx in nxlist:
    dx = 1. / (nx)

    args = " mesh:nx="+str(nx+4)+" mesh:dx="+str(dx)+" MZ="+str(nx)

    cmd = "./test_interpolate"+args

    shell("rm data/BOUT.dmp.*.nc")

    s, out = launch_safe(cmd, runcmd=MPIRUN, nproc=nproc, pipe=True)
    with open("run.log."+str(nx), "w") as f:
        f.write(out)

    # Collect output data
    for var in varlist:
        interp = collect(var+"_interp", path="data", xguards=False, info=False)
        solution = collect(var+"_solution", path="data", xguards=False, info=False)

        E = interp - solution

        l2 = sqrt(mean(E**2))
        linf = max(abs(E))

        error_2[var].append( l2 )
        error_inf[var].append( linf )

        print("{0:s} : l-2 {1:.8f} l-inf {2:.8f}".format(var, l2, linf))

dx = 1./array(nxlist)

# plot errors
plt.figure()

# Calculate convergence order
for var,mark,label in zip(varlist, markers, labels):
    plt.plot(dx, error_2[var], '-'+mark, label=label)
    plt.plot(dx, error_inf[var], '--'+mark)

    fit = polyfit(log(dx), log(error_2[var]), 1)
    order = fit[0]
    stdout.write("{0:s} Convergence order = {1:.2f}".format(var, order))

    if order < 2.5: # Should be third order accurate
        print("............ FAIL")
        success = False
    else:
        print("............ PASS")

plt.legend(loc="upper left")
plt.grid()

plt.yscale('log')
plt.xscale('log')

plt.xlabel(r'Mesh spacing $\delta x$')
plt.ylabel("Error norm")

plt.savefig("norm.pdf")

plt.show()
plt.close()

if success:
    print(" => All Interpolation tests passed")
    exit(0)
else:
    print(" => Some failed tests")
    exit(1)
