from sympy import symbols, cos, sin, tan, exp, log, pi
from boutdata.mms_alternate import *
from sys import exit

global metric

# Define non-trivial metrics
geometry = SimpleTokamak(dr=0.02, zperiod=600, r0=.0001, q=lambda x: .5+0.1*x)
#geometry = ShapedTokamak()
#geometry = ShapedTokamak(Rmaj=2., rmin=.2, dr=0.02)

# Define manufactured solution in toroidal x, y=theta, z=phi
# (where x is a radial coordinate going from zero to one across our domain)
solution = sin(x*pi)*exp(sin(3*z)) + tan(sin(2*x*pi))*log(2. + sin(z + 1.7))

# Shift solution to field-aligned coordinates
solution = solution.subs(z, z+metric.zShift)

# Calculate input

input = Delp2(solution)

# Print input file to stdout

print("# Generated by mms.py")
print("")
print("non_uniform = false") # Not supported by AMG solver yet
print("")
print("myg = 1")
print("mxg = 1")
print("")
print("solution = "+exprToStr(solution))
print("input = "+exprToStr(input))
print("")
print("[mesh]")
print("")
print("symmetricGlobalX = true")
print("")
print("nx = 34")
print("ny = nx-2*mxg")
print("nz = nx-2*mxg")
print("")
geometry.print_mesh()
print("")
print("[laplace]")
print("")
print("type = petscamg")
print("flags = 0")
print("")
print("[petscamg]")
print("solvertype = hy")

exit(0)
