# Makefile for example codes
# Works in the same way as the root Makefile

BOUT_TOP	= ..

DIRS		= advect1d rayleigh-taylor drift-instability \
                  lapd-drift orszag-tang interchange-instability \
                  rb-tokamak shear-alfven-wave uedge-benchmark advdiff

include $(BOUT_TOP)/make.config
