# Makefile for example codes
# Works in the same way as the root Makefile

BOUT_TOP	= ..

DIRS		= advect1d rayleigh-taylor drift-instability \
                  lapd-drift orszag-tang interchange-instability \
                  rb-tokamak shear-alfven-wave uedge-benchmark advdiff

CHECKDIRS	= test-io test-fieldfactory test-laplace test-cyclic \
		  test-invpar test-smooth test-gyro test-delp2 test-griddata \
		  MMS drift-instability interchange-instability

include $(BOUT_TOP)/make.config
