#!/usr/bin/env python

#
# Run the test suite, report failures
#
# To set command for running parallel jobs, define environment variable
# e.g. for bash
# export MPIRUN="mpirun -np"
# export MPIRUN="aprun -n"

from __future__ import print_function
import os
from boututils.run_wrapper import shell

# List of directories containing test cases
tests = ['test-io', 'test-field', 'test-fieldfactory', 'test-laplace', 
         "test-cyclic", "test-invpar", "test-smooth", "test-gyro",
         "test-delp2", "test-minmax",
         "MMS/diffusion","MMS/wave-1d",
         "drift-instability", 'interchange-instability']

##################################################################

savepath = os.getcwd() # Save current working directory
npassed = 0
nfailed = 0
total = len(tests)
failed = []
for t in tests:
    os.chdir(t)

    status,out = shell("make")

    if status != 0:
        print("Make test failed")
        nfailed = nfailed + 1
        failed.append(t)
    else:
        npassed = npassed + 1
    os.chdir(savepath)

print("=============================")
print("PASSED: %d / %d" % (npassed, total))
print("FAILED: %d / %d" % (nfailed, total))
print("")

if nfailed > 0:
    print("The following make tests failed")
    for t in failed:
        print("   "+t)
    import sys
    sys.exit(1)
else:
    print(" => All make tests passed <=")

print("")
