#!/usr/bin/env python

#
# Run the test suite, report failures
#
# To set command for running parallel jobs, define environment variable
# e.g. for bash
# export MPIRUN="mpirun -np"
# export MPIRUN="aprun -n"


# List of directories containing test cases
from __future__ import print_function
tests = ['test-io', 'test-fieldfactory', 'test-laplace',
         "test-cyclic", "test-invpar", "test-smooth", "test-gyro",
         "test-delp2", "test-griddata",
         "MMS/diffusion","MMS/wave-1d","MMS/wave-1d-y",
         "drift-instability", 'interchange-instability']

##################################################################

import os
from boututils.run_wrapper import shell

savepath = os.getcwd() # Save current working directory
npassed = 0
nfailed = 0
total = len(tests)
failed = []
for t in tests:
    os.chdir(t)

    status,out = shell("./runtest")

    if status != 0:
        print("Test failed")
        nfailed = nfailed + 1
        failed.append(t)
    else:
        npassed = npassed + 1
    os.chdir(savepath)

print("=============================")
print("PASSED: %d / %d" % (npassed, total))
print("FAILED: %d / %d" % (nfailed, total))
print("")

if nfailed > 0:
    print("The following tests failed")
    for t in failed:
        print("   "+t)
else:
    print(" => All tests passed <=")

print("")
