#!/usr/bin/env python

#
# Run the test suite, report failures
#
# To set command for running parallel jobs, define environment variable
# e.g. for bash
# export MPIRUN="mpirun -np"
# export MPIRUN="aprun -n"

from __future__ import print_function


# Get list of directories containing test cases
tests=[]
with open('test_suite_list') as testfile:
    for test in testfile:
        test=test.strip()
        if test.startswith("#"):
            pass
        elif test.startswith("!"):
            tests.append(test[1:])
        else:
            tests.append(test)

##################################################################

import os
from boututils.run_wrapper import shell

savepath = os.getcwd() # Save current working directory
npassed = 0
nfailed = 0
total = len(tests)
failed = []
for t in tests:
    os.chdir(t)

    status,out = shell("./runtest")

    if status != 0:
        print("Test failed")
        nfailed = nfailed + 1
        failed.append(t)
    else:
        npassed = npassed + 1
    os.chdir(savepath)

print("=============================")
print("PASSED: %d / %d" % (npassed, total))
print("FAILED: %d / %d" % (nfailed, total))
print("")

if nfailed > 0:
    print("The following tests failed")
    for t in failed:
        print("   "+t)
    import sys
    sys.exit(1)
else:
    print(" => All tests passed <=")

print("")
