
BOUT_TOP = ../..

SOURCEC		= field.cpp field2d.cpp field3d.cpp fieldperp.cpp initialprofiles.cpp vecops.cpp vector2d.cpp vector3d.cpp where.cpp
SOURCEH		= $(SOURCEC:%.cpp=%.h) field_data.h
TARGET		= lib

include $(BOUT_TOP)/make.config