
BOUT_TOP = ../..

DIRS            = impls
SOURCEC		= difops.cxx griddata.cxx interpolation.cxx mesh.cxx boundary_standard.cxx boundary_factory.cxx boundary_region.cxx meshfactory.cxx surfaceiter.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.hxx)
TARGET		= lib

include $(BOUT_TOP)/make.config
