#!/usr/bin/env python3

# Python script to run and analyse MMS test

import sys

from boutdata.collect import collect
from boututils.run_wrapper import build_and_log, launch_safe, shell
from numpy import abs, array, concatenate, log, max, mean, sqrt

build_and_log("Making MMS wave test")

# List of NX values to use
nxlist = [8, 12, 20, 36, 68, 132]

nout = 1
timestep = 0.1

nproc = 1

error_2 = []  # The L2 error (RMS)
error_inf = []  # The maximum error

for nx in nxlist:
    # Set mesh size and outputs. Replace previous outputs if present.
    args = (
        "mesh:nx="
        + str(nx)
        + " nout="
        + str(nout)
        + " timestep="
        + str(timestep)
        + " replace"
    )

    print("Running with " + args)

    # Delete old data
    shell("rm data/BOUT.dmp.*.nc")

    # Command to run
    cmd = "./wave " + args
    # Launch using MPI
    s, out = launch_safe(cmd, nproc=nproc, pipe=True)

    # Save output to log file
    with open("run.log." + str(nx), "w") as f:
        f.write(out)

    # Collect data
    E_f = collect("E_f", tind=[nout, nout], path="data", info=False)
    E_f = E_f[0, :, 0, 0]

    E_g = collect("E_g", tind=[nout, nout], path="data", info=False)
    E_g = E_g[0, :, 0, 0]

    # Average error over domain, not including guard cells
    E = concatenate([E_f[1:-1], E_g[2:-1]])

    l2 = sqrt(mean(E**2))
    linf = max(abs(E))

    error_2.append(l2)
    error_inf.append(linf)

    print("fError norm: l-2 {l2} l-inf {linf}")

# Calculate grid spacing
dx = 1.0 / (array(nxlist) - 2.0)

order = log(error_2[-1] / error_2[-2]) / log(dx[-1] / dx[-2])
print(f"Convergence order = {order}")

# plot errors
try:
    import matplotlib.pyplot as plt

    plt.plot(dx, error_2, "-o", label=r"$l^2$")
    plt.plot(dx, error_inf, "-x", label=r"$l^\infty$")
    plt.plot(dx, error_2[-1] * (dx / dx[-1]) ** order, "--", label="Order {order:.1f}")

    plt.legend(loc="upper left")
    plt.grid()

    plt.yscale("log")
    plt.xscale("log")

    plt.xlabel(r"Mesh spacing $\delta x$")
    plt.ylabel("Error norm")

    plt.savefig("wave_norm.pdf")

    # plt.show()
    plt.close()
except Exception as e:  # noqa: BLE001
    # Plotting could fail for any number of reasons, and the actual
    # error raised may depend on, among other things, the current
    # matplotlib backend, so catch everything
    print(f"Plotting: Caught exception {e}")

if 2.2 > order > 1.8:
    # test for success
    print(" => Test passed")
    sys.exit(0)
else:
    print(" => Test failed")
    sys.exit(1)
