#!/bin/bash

make

test ".$MPIRUN" = "." && MPIRUN="mpirun -np"

$MPIRUN 4 ./testVec  > log.4

exit=$?

if test $exit -gt 0
then
    echo "Failed to vector communication test"
    exit $exit
fi

echo "Test successfull."
