
BOUT_TOP = ../../../../..

SOURCEC         = multigrid_laplace.cxx multigrid_alg.cxx multigrid_solver.cxx
SOURCEH         = multigrid_laplace.hxx
TARGET          = lib

include $(BOUT_TOP)/make.config
