
BOUT_TOP = ../../../../..

SOURCEC         = multigrid_laplace.cxx multigrid_cycle.cxx multigrid_gmres.cxx
SOURCEH         = multigrid_laplace.hxx
TARGET          = lib

include $(BOUT_TOP)/make.config
