from builtins import str
from builtins import range
# Plot interpolating functions
# Input generated by simple_test.py

from numpy import linspace
import matplotlib.pyplot as plt
from boutdata.collect import collect

f = collect("f", path="data")
yup = collect("yup", path="data")

ny = 20
nz = 8

# Note: yup[y=0] is never set
y = linspace(-1, 1, ny-1)

plt.plot(f[0,4,4,:], 'o', label="f")

for z in range(nz):
    plt.plot(y+z, yup[4,1:,z], label="z = "+str(z))

plt.legend(loc='upper center')

plt.savefig("plot_funcs.pdf")

plt.show()
