BOUT_TOP	= ../../..
SOURCEH =
SOURCEC = subdirs.cxx

# make sure we extract the folder
# DIRS = fuu bar would work as well, but we want to make sure
# ../otherproject/fuu and /some/long/path/bar works as well ...
DIRS = fuu/ ././bar/

include $(BOUT_TOP)/make.config
