#!/usr/bin/env python3

# Tests if build has 3D metric

import os
from sys import exit
from boututils.run_wrapper import shell

selflocation = os.path.realpath(__file__)
selflocation = os.path.dirname(selflocation)
status, out = shell(selflocation + "/../../bin/bout-config --metric-type", pipe=True)

if "3D" in out:
    exit(0)  # True

exit(1)  # False
