#!/usr/bin/env bash

# Tests if mpich is being used
# NOTE: A more robust method is needed!

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

cxx=$($SCRIPTPATH/../../bin/bout-config --cxx)

cxx=$(which $cxx)

cxx_=
all=
while :
do
    all="$all $cxx"
    cxx__=$(readlink $cxx)
    test "$cxx__" || break
    cxx_=$(which $cxx__)
    echo $cxx_
    test ".$cxx_" == ".$cxx" && break
    cxx=$cxx_
done

if echo "$all"|grep mpich
then
    exit 0
else
    exit 1
fi

