#!/usr/bin/env python

# Tests if mpich is being used
# NOTE: A more robust method is needed!

from boututils.run_wrapper import shell
from sys import exit

# Test working on ubuntu
s, mpich = shell("which mpirun.mpich 2>/dev/null", pipe=True)
if s == 0:
    s, _ = shell("diff $(which mpirun) %s &>/dev/null"%mpich,
                 pipe=True)
    if s == 0:
        exit(0)  # True

# Test working on fedora
s, _ = shell("which mpirun | grep mpich &>/dev/null", pipe=True)

if s == 0:
    exit(0)  # True

exit(1)  # False
