#!/usr/bin/env sh

#requires: all_tests

set -ex

make -s


rm -rf test_backup
ln -s ../test-datadir/test test_backup

rm -rf data/BOUT.log*
rm -rf data/BOUT.set*


# make some old files
touch -r runtest data/BOUT.log.0
touch -r runtest data/BOUT.settings
./test_backup

# ensure both logs are still present
test -f data/BOUT.log.0
test -f data/BOUT.log.0~0

# ensure the backup is older
test data/BOUT.log.0 -nt data/BOUT.log.0~0

# same for settings file
test -f data/BOUT.settings
test -f data/BOUT.settings~0

test data/BOUT.settings -nt data/BOUT.settings~0
