
BOUT_TOP = ../../../..

SOURCEC		= pvode.cpp
SOURCEH		= $(SOURCEC:%.cpp=%.h)
INCLUDE		= -I../../../sys -I../../../field -I../../../physics -I../../../mesh -I../../../fileio -I../..
TARGET		= lib

include $(BOUT_TOP)/make.config
