#!/usr/bin/env sh

make > make.log || exit

for n in 1 2 4
do
    for m in 1 2 3 4 5
    do
	if ! OMP_NUM_THREADS=$m mpirun -np $n ./test_dataiterator > run.log.$m.$n
        then
            err=$?
            echo failing command was:
            echo OMP_NUM_THREADS=$m mpirun -np $n ./test_dataiterator
            echo
            echo error log was:
            cat run.log.$m.$n
            echo
            exit $?
        fi
    done
done

echo "All test successfull"
