
BOUT_TOP = ../../../..

DIRS		= impls
SOURCEC		= rkgeneric.cxx rkschemefactory.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.hxx)
INCLUDE		= -Iimpls/rkf45 -Iimpls/cashkarp
TARGET		= lib

include $(BOUT_TOP)/make.config
