#!/bin/bash

if [[ -z $1 ]]; then
	echo "give an argument"
	exit 1
fi

avg() {
    awk 'BEGIN {FS=":"}; {sum+=$3; sum2+=$4} END {print sum2/NR}'
}

for i in $(seq 1 500)
do mpirun -n 4 ./iterator >/dev/null
    mv -v ./data/BOUT.log.0 ./data/run_$i
done
echo -e "\a"

nested=$(grep "Nested:" ./data/run_* | avg)
c_loop=$(grep "C loop:" ./data/run_* | avg)
iter=$(grep -E "^Iterator:" ./data/run_* | avg)
field=$(grep "Field Iterator:" ./data/run_* | avg)
range=$(grep "Range-based:" ./data/run_* | avg)
foreach=$(grep "For_each:" ./data/run_* | avg)

nested_single=$(grep "Nested (single):" ./data/run_* | avg)
c_loop_single=$(grep "C loop (single):" ./data/run_* | avg)
iter_single=$(grep -E "^Iterator \(single\):" ./data/run_* | avg)
field_single=$(grep "Range-based (field)" ./data/run_* | avg)
mesh_single=$(grep "Range-based (mesh)" ./data/run_* | avg)

nested_norm=$(echo "scale=2;$nested / $c_loop" | bc -l)
c_loop_norm=$(echo "scale=2;$c_loop / $c_loop" | bc -l)
iter_norm=$(echo "scale=2;$iter / $c_loop" | bc -l)
field_norm=$(echo "scale=2;$field / $c_loop" | bc -l)
range_norm=$(echo "scale=2;$range / $c_loop" | bc -l)
foreach_norm=$(echo "scale=2;$foreach / $c_loop" | bc -l)

nested_single_norm=$(echo "scale=2;$nested_single / $c_loop_single" | bc -l)
c_loop_single_norm=$(echo "scale=2;$c_loop_single / $c_loop_single" | bc -l)
iter_single_norm=$(echo "scale=2;$iter_single / $c_loop_single" | bc -l)
field_single_norm=$(echo "scale=6;${field_single/e/*10^} / $c_loop_single" | bc -l)
mesh_single_norm=$(echo "scale=2;$mesh_single / $c_loop_single" | bc -l)

echo -e "Three Field operation
=====================
Nested		 $nested  $nested_norm
C_loop		 $c_loop  $c_loop_norm
Iterator	 $iter  $iter_norm
Field_iterator	 $field  $field_norm
Range-based	 $range  $range_norm
For_each	 $foreach  $foreach_norm

Single Field operation
======================
Nested  	    $nested_single  $nested_single_norm
C_loop  	    $c_loop_single  $c_loop_single_norm
Iterator 	    $iter_single  $iter_single_norm
Range-based_(field) $field_single  $field_single_norm
Range-based_(mesh)  $mesh_single  $mesh_single_norm" > $1
