#!/bin/bash

if [[ -z $1 ]]; then
	echo "give an argument"
	exit 1
fi

avg() {
    awk 'BEGIN {FS=":"}; {sum+=$3} END {print sum/NR}'
}

get_value() {
    grep "$1" ./data/run_* | avg
}

for i in $(seq 1 500)
do mpirun -n 4 ./iterator >/dev/null
    mv -v ./data/BOUT.log.0 ./data/run_$i
done
echo -e "\a"

nested=$(get_value "Nested (data)")
c_loop=$(get_value "C loop (data)")
miter=$(get_value "MeshIterator (data)")
diter_data=$(get_value "DataIterator (data)")
diter_data_done=$(get_value "DataIterator (data/done())")
range_data=$(get_value "Range-based (data)")
freach_data=$(get_value "For_each (data)")
nested_field=$(get_value "Nested (field)")
range_field=$(get_value "Range-based (field)")
diter_field=$(get_value "DataIterator (field)")
freach_field=$(get_value "For_each (field)")

norm() {
    echo "scale=2;$1 / $nested_field" | bc -l
}

nested_norm=$(norm $nested)
c_loop_norm=$(norm $c_loop)
miter_norm=$(norm $miter)
diter_data_norm=$(norm $diter_data)
diter_data_done_norm=$(norm $diter_data_done)
range_data_norm=$(norm $range_data)
freach_data_norm=$(norm $freach_data)
nested_field_norm=$(norm $nested_field)
range_field_norm=$(norm $range_field)
diter_field_norm=$(norm $diter_field)
freach_field_norm=$(norm $freach_field)

echo -e "Timings
=======" > $1
echo -e "Nested (data)			: $nested : $nested_norm
C loop (data)			: $c_loop : $c_loop_norm
MeshIterator (data)		: $miter : $miter_norm
DataIterator (data)		: $diter_data : $diter_data_norm
DataIterator (data/done())	: $diter_data_done : $diter_data_done_norm
Range-based (data)		: $range_data : $range_data_norm
For_each (data)			: $freach_data : $freach_data_norm
Nested (field)			: $nested_field : $nested_field_norm
Range-based (field)		: $range_field : $range_field_norm
DataIterator (field)		: $diter_field : $diter_field_norm
For_each (field)		: $freach_field : $freach_field_norm" | sort -rt ":" -k2 >> $1

