
BOUT_TOP = ../..

SOURCEC		= boundary.cpp smoothing.cpp  sourcex.cpp
SOURCEH		= $(SOURCEC:%.cpp=%.h)
INCLUDE		= -I../sys -I../field -I../invert -I../mesh -I../fileio
TARGET		= lib

include $(BOUT_TOP)/make.config