#!/bin/bash

#requires boutcore
#requires all_tests
#requires not make

# With no aruments, this script runs the test at high resolution, but skipping
# cases that would require 3D grids. Checking is performed that exceptions are
# thrown for inputs, e.g. combinations of locations, that are not allowed.

PYTHONPATH=../../../tools/pylib/:$PYTHONPATH python3 runtest.py $@

exit 0
