name: format-command

on:
  pull_request:

jobs:
  clang-format:
    # Release candidate branches tend to have big PRs which causes all sorts of problems
    if: ${{ !endsWith(github.head_ref, '-rc') }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch, also include all history
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # This also installs git-clang-format
      - name: Install formatters
        run: |
          sudo apt install clang-format python3-pip python3-setuptools python3-wheel
          pip3 install ruff cmake-format

      - name: Version
        run: |
          python3 --version
          $HOME/.local/bin/ruff --version
          clang-format --version
          $HOME/.local/bin/cmake-format --version

      - name: Run clang-format
        id: format
        run:
          while ! git clang-format origin/${{ github.base_ref }} ; do git add . ; done

      - name: Run ruff
        run: |
          pwd
          ls
          $HOME/.local/bin/ruff format .
          
      - name: Run cmake-format
        run: |
          pwd
          ls
          $HOME/.local/bin/cmake-format -i $(find -name CMakeLists.txt) cmake/*.cmake

      - name: Commit formatting
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[bot] Apply format changes"
          skip_push: true

      - name: Ignore formatting
        run: |
          msg=$(git rev-list --format=%s --max-count=1 HEAD|tail -n -1)
          test "$msg" = "[bot] Apply format changes" && git rev-parse HEAD >> .git-blame-ignore-revs || :

      - name: Commit formatting
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[bot] Add last format changes commit to ignore file"

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.23.1
        id: review
        with:
          build_dir: build
          apt_packages: "libfftw3-dev,libnetcdf-c++4-dev,libopenmpi-dev,petsc-dev,slepc-dev,liblapack-dev,libparpack2-dev,libsundials-dev,uuid-dev"
          config_file: ".clang-tidy"
          # Googletest triggers a _lot_ of clang-tidy warnings, so ignore all
          # the unit tests until they're fixed or ignored upstream
          exclude: "tests/unit/*cxx"
          lgtm_comment_body: ''
          cmake_command: |
            git config --global --add safe.directory /github/workspace && \
            git submodule update --init --recursive --recommend-shallow && \
            pip install --break-system-packages cmake && \
            cmake --version && \
            git config --global --add safe.directory "$GITHUB_WORKSPACE" && \
            cmake . -B build -DBUILD_SHARED_LIBS=ON \
                             -DBOUT_USE_PETSC=ON \
                             -DBOUT_USE_SLEPC=ON \
                             -DBOUT_USE_SUNDIALS=ON \
                             -DBOUT_BUILD_EXAMPLES=ON \
                             -DBOUT_BUILD_DOCS=OFF \
                             -DBOUT_ENABLE_PYTHON=OFF \
                             -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
                             -DBOUT_UPDATE_GIT_SUBMODULE=OFF

      - name: Upload clang-tidy fixes
        uses: ZedThree/clang-tidy-review/upload@v0.23.1
